# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190125_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
